
name: CSS Validation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Files # https://github.com/marketplace/actions/html5-validator
        uses: Cyb3r-Jak3/html5validator-action@v7.0.0
        with:
          root: ./css
          log_level: INFO
          css: TRUE
      - uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.log
