name: Validation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      
      - name: HTML Validation
        uses: Cyb3r-Jak3/html5validator-action@v7.0.0
        with:
          root: .
          log_level: INFO
        
      - name: CSS Validation
        uses: Cyb3r-Jak3/html5validator-action@v7.0.0
        with:
          root: ./css
          log_level: INFO
          css: TRUE
